/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface EuiEditorPanelGroup {
    'title': string;
  }
  interface EuiEditorPanelGroupAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface EuiEditorPanel {
    'title': string;
  }
  interface EuiEditorPanelAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface EuiLayoutResizable {
    'axis': "x" | "y" | "xy";
    'height': number;
    'maxHeight': number;
    'maxWidth': number;
    'minHeight': number;
    'minWidth': number;
    'width': number;
  }
  interface EuiLayoutResizableAttributes extends StencilHTMLAttributes {
    'axis'?: "x" | "y" | "xy";
    'height'?: number;
    'maxHeight'?: number;
    'maxWidth'?: number;
    'minHeight'?: number;
    'minWidth'?: number;
    'width'?: number;
  }

  interface EuiLayoutScrollable {
    'axis': "x" | "y" | "xy";
  }
  interface EuiLayoutScrollableAttributes extends StencilHTMLAttributes {
    'axis'?: "x" | "y" | "xy";
  }

  interface EuiLayoutSplit {
    'colWidth': string;
    'splitDir': "vertical" | "horizontal";
  }
  interface EuiLayoutSplitAttributes extends StencilHTMLAttributes {
    'colWidth'?: string;
    'splitDir'?: "vertical" | "horizontal";
  }
}

declare global {
  interface StencilElementInterfaces {
    'EuiEditorPanelGroup': Components.EuiEditorPanelGroup;
    'EuiEditorPanel': Components.EuiEditorPanel;
    'EuiLayoutResizable': Components.EuiLayoutResizable;
    'EuiLayoutScrollable': Components.EuiLayoutScrollable;
    'EuiLayoutSplit': Components.EuiLayoutSplit;
  }

  interface StencilIntrinsicElements {
    'eui-editor-panel-group': Components.EuiEditorPanelGroupAttributes;
    'eui-editor-panel': Components.EuiEditorPanelAttributes;
    'eui-layout-resizable': Components.EuiLayoutResizableAttributes;
    'eui-layout-scrollable': Components.EuiLayoutScrollableAttributes;
    'eui-layout-split': Components.EuiLayoutSplitAttributes;
  }


  interface HTMLEuiEditorPanelGroupElement extends Components.EuiEditorPanelGroup, HTMLStencilElement {}
  var HTMLEuiEditorPanelGroupElement: {
    prototype: HTMLEuiEditorPanelGroupElement;
    new (): HTMLEuiEditorPanelGroupElement;
  };

  interface HTMLEuiEditorPanelElement extends Components.EuiEditorPanel, HTMLStencilElement {}
  var HTMLEuiEditorPanelElement: {
    prototype: HTMLEuiEditorPanelElement;
    new (): HTMLEuiEditorPanelElement;
  };

  interface HTMLEuiLayoutResizableElement extends Components.EuiLayoutResizable, HTMLStencilElement {}
  var HTMLEuiLayoutResizableElement: {
    prototype: HTMLEuiLayoutResizableElement;
    new (): HTMLEuiLayoutResizableElement;
  };

  interface HTMLEuiLayoutScrollableElement extends Components.EuiLayoutScrollable, HTMLStencilElement {}
  var HTMLEuiLayoutScrollableElement: {
    prototype: HTMLEuiLayoutScrollableElement;
    new (): HTMLEuiLayoutScrollableElement;
  };

  interface HTMLEuiLayoutSplitElement extends Components.EuiLayoutSplit, HTMLStencilElement {}
  var HTMLEuiLayoutSplitElement: {
    prototype: HTMLEuiLayoutSplitElement;
    new (): HTMLEuiLayoutSplitElement;
  };

  interface HTMLElementTagNameMap {
    'eui-editor-panel-group': HTMLEuiEditorPanelGroupElement
    'eui-editor-panel': HTMLEuiEditorPanelElement
    'eui-layout-resizable': HTMLEuiLayoutResizableElement
    'eui-layout-scrollable': HTMLEuiLayoutScrollableElement
    'eui-layout-split': HTMLEuiLayoutSplitElement
  }

  interface ElementTagNameMap {
    'eui-editor-panel-group': HTMLEuiEditorPanelGroupElement;
    'eui-editor-panel': HTMLEuiEditorPanelElement;
    'eui-layout-resizable': HTMLEuiLayoutResizableElement;
    'eui-layout-scrollable': HTMLEuiLayoutScrollableElement;
    'eui-layout-split': HTMLEuiLayoutSplitElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
